package transema.backend.astAnalyser;

import org.kframework.attributes.Source;
import org.kframework.definition.Module;
import org.kframework.definition.Rule;
import org.kframework.kompile.CompiledDefinition;
import org.kframework.main.GlobalOptions;
import org.kframework.utils.BinaryLoader;
import org.kframework.utils.errorsystem.KExceptionManager;
import scala.Option;
import scala.collection.Iterator;
import scala.collection.Set;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

public class SemaRulesLoader {
    static final String SEMA_MODULE_NAME = "X86-INSTRUCTIONS-SEMANTICS";
    static final String SEMA_SOURCE_PATH = "x86-instructions-semantics.k";

    static private String translateISELToXEDFormat(String iselK) {
        // TODO: generalize approach, probably use map file generated by XED+Kframework
        if (Objects.equals(iselK, "MOVQ-R64-R64")){
            return "ISEL_MOV_GPRv_GPRv_89_64";
        } else if (Objects.equals(iselK, "MOVQ-R64-IMM64")) {
            return "ISEL_MOV_GPRv_IMMv_64";
        } else if (Objects.equals(iselK, "MOVQ-R64-M64")) {
            return "ISEL_MOV_GPRv_MEMv_64";
        } else {
            System.err.println("translateISELToXEDFormat: unknown mapping for k isel "+iselK);
        }

        return iselK;
    }

    static public Map<String, Rule> getSemanticFunctionRules(CompiledDefinition def) {
        Map<String, Rule> iselToRule = new HashMap<>();

        Option<Module> instructionSemaModuleOpt = def
                .getParsedDefinition()
                .getModule(SEMA_MODULE_NAME);

        if(instructionSemaModuleOpt.isDefined()){
            Module instructionSemaModule = instructionSemaModuleOpt.get();
            Set<Rule> instructionSemaRules = instructionSemaModule.rules();

            Iterator<Rule> it = instructionSemaRules.iterator();
            while(it.hasNext()) {
                Rule r = it.next();
                if (r.isNonSyntax()) {
                    Optional<Source> s = r.source();
                    if (s.isPresent() && s.get().source().endsWith(SEMA_SOURCE_PATH)) {
                        Option<String> klabel = r.att().getOption("klabel");
                        if(klabel.isDefined()) {
                            String xedISEL = translateISELToXEDFormat(klabel.get());
                            iselToRule.put(xedISEL, r);
                        }
                    }
                }
            }
        } else {
            throw new IllegalArgumentException("Module <" + SEMA_MODULE_NAME + "> is not defined");
        }

        return iselToRule;
    }

    public Map<String, Rule> load(String filePath) throws IOException, ClassNotFoundException, InterruptedException {
        BinaryLoader bl = new BinaryLoader(new KExceptionManager(new GlobalOptions()));
        CompiledDefinition def = (CompiledDefinition) bl.loadSynchronized(new File(filePath));
        return getSemanticFunctionRules(def);
    }
}
