/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class transema_codegen_TransemaCodegen */

#ifndef _Included_transema_codegen_TransemaCodegen
#define _Included_transema_codegen_TransemaCodegen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     transema_codegen_TransemaCodegen
 * Method:    createNewModule
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_transema_codegen_TransemaCodegen_createNewModule
  (JNIEnv *, jobject, jstring);

/*
 * Class:     transema_codegen_TransemaCodegen
 * Method:    emit
 * Signature: (Ltransema/SemanticFunction;)V
 */
JNIEXPORT void JNICALL Java_transema_codegen_TransemaCodegen_emit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     transema_codegen_TransemaCodegen
 * Method:    cleanNativeState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_transema_codegen_TransemaCodegen_cleanNativeState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
